import Mock from "../mock";

const ListDB = {
  list: [
    {
      id: 1,
      email: "uilib@gmail.com",
      userName: "ui lib",
      projectName: "Maqhekung Phase",
      date: new Date().toLocaleString(),
      projectImage: "/assets/images/1.jfif",
      userImage: "/assets/images/face-1.jpg",
      comment: 200,
      revision: 5,
    },
    {
      id: 2,
      email: "uilib@gmail.com",
      userName: "ui lib",
      projectName: "Mediclinic Housig Developmet",
      date: new Date().toLocaleString(),
      projectImage: "/assets/images/2.jfif",
      userImage: "/assets/images/face-1.jpg",
      comment: 1500,
      revision: 5,
    },
    {
      id: 3,
      email: "uilib@gmail.com",
      userName: "ui lib",
      projectName: "Taung Housig Developmet",
      date: new Date().toLocaleString(),
      projectImage: "/assets/images/2.png",
      userImage: "/assets/images/face-1.jpg",
      comment: 340,
      revision: 5,
    },
    {
      id: 5,
      email: "uilib@gmail.com",
      userName: "ui lib",
      projectName: "Gull development",
      date: new Date().toLocaleString(),
      projectImage: "/assets/images/4.jpg",
      userImage: "/assets/images/face-1.jpg",
      comment: 280,
      revision: 5,
    },
    {
      id: 6,
      email: "uilib@gmail.com",
      userName: "ui lib",
      projectName: "Evalynn development",
      date: new Date().toLocaleString(),
      projectImage: "/assets/images/5.jpg",
      userImage: "/assets/images/face-1.jpg",
      comment: 0,
      revision: 5,
    },
    {
      id: 7,
      email: "uilib@gmail.com",
      userName: "ui lib",
      projectName: "Dexum development",
      date: new Date().toLocaleString(),
      projectImage: "/assets/images/6.jpg",
      userImage: "/assets/images/face-1.jpg",
      comment: 0,
      revision: 5,
    },
    {
      id: 8,
      email: "uilib@gmail.com",
      userName: "ui lib",
      projectName: "Grootvlei Project",
      date: new Date().toLocaleString(),
      projectImage: "/assets/images/7.jpg",
      userImage: "/assets/images/face-1.jpg",
      comment: 0,
      revision: 5,
    },
    {
      id: 9,
      email: "uilib@gmail.com",
      userName: "ui lib",
      projectName: "Sehlabeng development",
      date: new Date().toLocaleString(),
      projectImage: "/assets/images/8.jpg",
      userImage: "/assets/images/face-1.jpg",
      comment: 250,
      revision: 5,
    },
  ],
};

Mock.onGet("/api/list/all").reply((config) => {
  const response = ListDB.list;
  return [200, response];
});
