import Mock from "../mock";

const ListDB = {
  list: [
    {
      id: 1,
      email: "uilib@gmail.com",
      userName: "ui lib",
      projectName: "Incident i Roads Project",
      date: new Date().toLocaleString(),
      projectImage: "/assets/images/1.png",
      userImage: "/assets/images/face-1.jpg",
      comment: 0,
      revision: 5,
    },
    {
      id: 2,
      email: "uilib@gmail.com",
      userName: "ui lib",
      projectName: "Housig Developmet Incident",
      date: new Date().toLocaleString(),
      projectImage: "/assets/images/4.png",
      userImage: "/assets/images/face-1.jpg",
      comment: 0,
      revision: 5,
    },
    {
      id: 3,
      email: "uilib@gmail.com",
      userName: "ui lib",
      projectName: "Incidents Report for Capetow",
      date: new Date().toLocaleString(),
      projectImage: "/assets/images/3.png",
      userImage: "/assets/images/face-1.jpg",
      comment: 0,
      revision: 5,
    },
    {
      id: 5,
      email: "uilib@gmail.com",
      userName: "ui lib",
      projectName: "Gull development Incidents",
      date: new Date().toLocaleString(),
      projectImage: "/assets/images/3.jpg",
      userImage: "/assets/images/face-1.jpg",
      comment: 0,
      revision: 5,
    },
    {
      id: 6,
      email: "uilib@gmail.com",
      userName: "ui lib",
      projectName: "Evalynn development Incidents",
      date: new Date().toLocaleString(),
      projectImage: "/assets/images/4.png",
      userImage: "/assets/images/face-1.jpg",
      comment: 0,
      revision: 5,
    },
    {
      id: 7,
      email: "uilib@gmail.com",
      userName: "ui lib",
      projectName: "Dexum development Incidents",
      date: new Date().toLocaleString(),
      projectImage: "/assets/images/1.png",
      userImage: "/assets/images/face-1.jpg",
      comment: 0,
      revision: 5,
    },
    {
      id: 8,
      email: "uilib@gmail.com",
      userName: "ui lib",
      projectName: "Tech Project Incidents",
      date: new Date().toLocaleString(),
      projectImage: "/assets/images/3.png",
      userImage: "/assets/images/face-1.jpg",
      comment: 0,
      revision: 5,
    },
    {
      id: 9,
      email: "uilib@gmail.com",
      userName: "ui lib",
      projectName: "Matx development Incidents",
      date: new Date().toLocaleString(),
      projectImage: "/assets/images/3.jpg",
      userImage: "/assets/images/face-1.jpg",
      comment: 0,
      revision: 5,
    },
  ],
};

Mock.onGet("/api/list/all").reply((config) => {
  const response = ListDB.list;
  return [200, response];
});
